version: "3.8"
services:
  detection:
    image: face-detector-stack/detection:1.0-SNAPSHOT

  extraction:
    image: face-detector-stack/extraction:1.0-SNAPSHOT

  embedding:
    image: face-detector-stack/embedding:1.0-SNAPSHOT

  query-builder:
    image: face-detector-stack/query-builder:1.0-SNAPSHOT
    ports:
     - 50051:50051
    environment:
      DETECTOR_HOSTNAME: "detection:50051"
      EXTRACTOR_HOSTNAME: "extraction:50051"
      EMBEDDER_HOSTNAME: "embedding:50051"


