version: "3.8"
services:
  detection:
    image: lamba92/face-detector-stack.detection:1.0-SNAPSHOT
    deploy:
      replicas: 5

  extraction:
    image: lamba92/face-detector-stack.extraction:1.0-SNAPSHOT

  embedding:
    image: lamba92/face-detector-stack.embedding:1.0-SNAPSHOT
    deploy:
      replicas: 5

  query-builder:
    image: lamba92/face-detector-stack.query-builder:1.0-SNAPSHOT
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: ingress
    environment:
      DETECTOR_HOSTNAME: "http://detection"
      EXTRACTOR_HOSTNAME: "http://extraction"
      EMBEDDER_HOSTNAME: "http://embedding"


