version: "3.8"
services:
  detection:
    image: face-detector-stack/detection:1.0-SNAPSHOT
    ports:
      - 8080:80
  extraction:
    image: face-detector-stack/extraction:1.0-SNAPSHOT
    ports:
      - 8081:80
  embedding:
    image: face-detector-stack/embedding:1.0-SNAPSHOT
    ports:
        - 8082:80
  query-builder:
    image: face-detector-stack/query-builder:1.0-SNAPSHOT
    ports:
      - 8083:80
    environment:
      DETECTOR_HOSTNAME: "http://detection"
      EXTRACTOR_HOSTNAME: "http://extraction"
      EMBEDDER_HOSTNAME: "http://embedding"


