# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comparison.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='comparison.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63omparison.proto\x1a\x0c\x63ommon.proto\"k\n\x11\x43omparisonRequest\x12\'\n\nembeddings\x18\x01 \x03(\x0b\x32\x13.EmbeddingContainer\x12-\n\x10other_embeddings\x18\x02 \x03(\x0b\x32\x13.EmbeddingContainer2@\n\nComparison\x12\x32\n\x07\x63ompare\x12\x12.ComparisonRequest\x1a\x13.ComparisonResponseb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_COMPARISONREQUEST = _descriptor.Descriptor(
  name='ComparisonRequest',
  full_name='ComparisonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='embeddings', full_name='ComparisonRequest.embeddings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='other_embeddings', full_name='ComparisonRequest.other_embeddings', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=141,
)

_COMPARISONREQUEST.fields_by_name['embeddings'].message_type = common__pb2._EMBEDDINGCONTAINER
_COMPARISONREQUEST.fields_by_name['other_embeddings'].message_type = common__pb2._EMBEDDINGCONTAINER
DESCRIPTOR.message_types_by_name['ComparisonRequest'] = _COMPARISONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComparisonRequest = _reflection.GeneratedProtocolMessageType('ComparisonRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPARISONREQUEST,
  '__module__' : 'comparison_pb2'
  # @@protoc_insertion_point(class_scope:ComparisonRequest)
  })
_sym_db.RegisterMessage(ComparisonRequest)



_COMPARISON = _descriptor.ServiceDescriptor(
  name='Comparison',
  full_name='Comparison',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=143,
  serialized_end=207,
  methods=[
  _descriptor.MethodDescriptor(
    name='compare',
    full_name='Comparison.compare',
    index=0,
    containing_service=None,
    input_type=_COMPARISONREQUEST,
    output_type=common__pb2._COMPARISONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPARISON)

DESCRIPTOR.services_by_name['Comparison'] = _COMPARISON

# @@protoc_insertion_point(module_scope)
