# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='embedding.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x65mbedding.proto\x1a\x0c\x63ommon.proto\"\"\n\x10\x45mbeddingRequest\x12\x0e\n\x06images\x18\x01 \x03(\t\"9\n\x11\x45mbeddingResponse\x12$\n\x07results\x18\x01 \x03(\x0b\x32\x13.EmbeddingContainer2;\n\tEmbedding\x12.\n\x05\x65mbed\x12\x11.EmbeddingRequest\x1a\x12.EmbeddingResponseb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_EMBEDDINGREQUEST = _descriptor.Descriptor(
  name='EmbeddingRequest',
  full_name='EmbeddingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='EmbeddingRequest.images', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=67,
)


_EMBEDDINGRESPONSE = _descriptor.Descriptor(
  name='EmbeddingResponse',
  full_name='EmbeddingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='EmbeddingResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=126,
)

_EMBEDDINGRESPONSE.fields_by_name['results'].message_type = common__pb2._EMBEDDINGCONTAINER
DESCRIPTOR.message_types_by_name['EmbeddingRequest'] = _EMBEDDINGREQUEST
DESCRIPTOR.message_types_by_name['EmbeddingResponse'] = _EMBEDDINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmbeddingRequest = _reflection.GeneratedProtocolMessageType('EmbeddingRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDDINGREQUEST,
  '__module__' : 'embedding_pb2'
  # @@protoc_insertion_point(class_scope:EmbeddingRequest)
  })
_sym_db.RegisterMessage(EmbeddingRequest)

EmbeddingResponse = _reflection.GeneratedProtocolMessageType('EmbeddingResponse', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDDINGRESPONSE,
  '__module__' : 'embedding_pb2'
  # @@protoc_insertion_point(class_scope:EmbeddingResponse)
  })
_sym_db.RegisterMessage(EmbeddingResponse)



_EMBEDDING = _descriptor.ServiceDescriptor(
  name='Embedding',
  full_name='Embedding',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=128,
  serialized_end=187,
  methods=[
  _descriptor.MethodDescriptor(
    name='embed',
    full_name='Embedding.embed',
    index=0,
    containing_service=None,
    input_type=_EMBEDDINGREQUEST,
    output_type=_EMBEDDINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMBEDDING)

DESCRIPTOR.services_by_name['Embedding'] = _EMBEDDING

# @@protoc_insertion_point(module_scope)
