# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='detection.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x64\x65tection.proto\x1a\x0c\x63ommon.proto\"\"\n\x10\x44\x65tectionRequest\x12\x0e\n\x06images\x18\x01 \x03(\t\"x\n\x11\x44\x65tectionResponse\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.DetectionResponse.Item\x1a;\n\x04Item\x12\r\n\x05image\x18\x01 \x01(\t\x12$\n\x0b\x61nnotations\x18\x02 \x03(\x0b\x32\x0f.FaceAnnotation2>\n\tDetection\x12\x31\n\x06\x64\x65tect\x12\x11.DetectionRequest\x1a\x12.DetectionResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_DETECTIONREQUEST = _descriptor.Descriptor(
  name='DetectionRequest',
  full_name='DetectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='DetectionRequest.images', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=67,
)


_DETECTIONRESPONSE_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='DetectionResponse.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='DetectionResponse.Item.image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='annotations', full_name='DetectionResponse.Item.annotations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=189,
)

_DETECTIONRESPONSE = _descriptor.Descriptor(
  name='DetectionResponse',
  full_name='DetectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='DetectionResponse.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DETECTIONRESPONSE_ITEM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=189,
)

_DETECTIONRESPONSE_ITEM.fields_by_name['annotations'].message_type = common__pb2._FACEANNOTATION
_DETECTIONRESPONSE_ITEM.containing_type = _DETECTIONRESPONSE
_DETECTIONRESPONSE.fields_by_name['items'].message_type = _DETECTIONRESPONSE_ITEM
DESCRIPTOR.message_types_by_name['DetectionRequest'] = _DETECTIONREQUEST
DESCRIPTOR.message_types_by_name['DetectionResponse'] = _DETECTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DetectionRequest = _reflection.GeneratedProtocolMessageType('DetectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONREQUEST,
  '__module__' : 'detection_pb2'
  # @@protoc_insertion_point(class_scope:DetectionRequest)
  })
_sym_db.RegisterMessage(DetectionRequest)

DetectionResponse = _reflection.GeneratedProtocolMessageType('DetectionResponse', (_message.Message,), {

  'Item' : _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
    'DESCRIPTOR' : _DETECTIONRESPONSE_ITEM,
    '__module__' : 'detection_pb2'
    # @@protoc_insertion_point(class_scope:DetectionResponse.Item)
    })
  ,
  'DESCRIPTOR' : _DETECTIONRESPONSE,
  '__module__' : 'detection_pb2'
  # @@protoc_insertion_point(class_scope:DetectionResponse)
  })
_sym_db.RegisterMessage(DetectionResponse)
_sym_db.RegisterMessage(DetectionResponse.Item)



_DETECTION = _descriptor.ServiceDescriptor(
  name='Detection',
  full_name='Detection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=191,
  serialized_end=253,
  methods=[
  _descriptor.MethodDescriptor(
    name='detect',
    full_name='Detection.detect',
    index=0,
    containing_service=None,
    input_type=_DETECTIONREQUEST,
    output_type=_DETECTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DETECTION)

DESCRIPTOR.services_by_name['Detection'] = _DETECTION

# @@protoc_insertion_point(module_scope)
