# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='embedding.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x65mbedding.proto\"\"\n\x10\x45mbeddingRequest\x12\x0e\n\x06images\x18\x01 \x03(\t\"^\n\x11\x45mbeddingResponse\x12-\n\x07results\x18\x01 \x03(\x0b\x32\x1c.EmbeddingResponse.Embedding\x1a\x1a\n\tEmbedding\x12\r\n\x05\x61rray\x18\x01 \x03(\x01\x32=\n\tEmbedding\x12\x30\n\x05\x65mbed\x12\x11.EmbeddingRequest\x1a\x12.EmbeddingResponse\"\x00\x62\x06proto3'
)




_EMBEDDINGREQUEST = _descriptor.Descriptor(
  name='EmbeddingRequest',
  full_name='EmbeddingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='EmbeddingRequest.images', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=53,
)


_EMBEDDINGRESPONSE_EMBEDDING = _descriptor.Descriptor(
  name='Embedding',
  full_name='EmbeddingResponse.Embedding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='array', full_name='EmbeddingResponse.Embedding.array', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=149,
)

_EMBEDDINGRESPONSE = _descriptor.Descriptor(
  name='EmbeddingResponse',
  full_name='EmbeddingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='EmbeddingResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EMBEDDINGRESPONSE_EMBEDDING, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=149,
)

_EMBEDDINGRESPONSE_EMBEDDING.containing_type = _EMBEDDINGRESPONSE
_EMBEDDINGRESPONSE.fields_by_name['results'].message_type = _EMBEDDINGRESPONSE_EMBEDDING
DESCRIPTOR.message_types_by_name['EmbeddingRequest'] = _EMBEDDINGREQUEST
DESCRIPTOR.message_types_by_name['EmbeddingResponse'] = _EMBEDDINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmbeddingRequest = _reflection.GeneratedProtocolMessageType('EmbeddingRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDDINGREQUEST,
  '__module__' : 'embedding_pb2'
  # @@protoc_insertion_point(class_scope:EmbeddingRequest)
  })
_sym_db.RegisterMessage(EmbeddingRequest)

EmbeddingResponse = _reflection.GeneratedProtocolMessageType('EmbeddingResponse', (_message.Message,), {

  'Embedding' : _reflection.GeneratedProtocolMessageType('Embedding', (_message.Message,), {
    'DESCRIPTOR' : _EMBEDDINGRESPONSE_EMBEDDING,
    '__module__' : 'embedding_pb2'
    # @@protoc_insertion_point(class_scope:EmbeddingResponse.Embedding)
    })
  ,
  'DESCRIPTOR' : _EMBEDDINGRESPONSE,
  '__module__' : 'embedding_pb2'
  # @@protoc_insertion_point(class_scope:EmbeddingResponse)
  })
_sym_db.RegisterMessage(EmbeddingResponse)
_sym_db.RegisterMessage(EmbeddingResponse.Embedding)



_EMBEDDING = _descriptor.ServiceDescriptor(
  name='Embedding',
  full_name='Embedding',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=151,
  serialized_end=212,
  methods=[
  _descriptor.MethodDescriptor(
    name='embed',
    full_name='Embedding.embed',
    index=0,
    containing_service=None,
    input_type=_EMBEDDINGREQUEST,
    output_type=_EMBEDDINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMBEDDING)

DESCRIPTOR.services_by_name['Embedding'] = _EMBEDDING

# @@protoc_insertion_point(module_scope)
