# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extraction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='extraction.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x65xtraction.proto\x1a\x0c\x63ommon.proto\"j\n\x11\x45xtractionRequest\x12\r\n\x05image\x18\x01 \x01(\t\x12$\n\x0b\x61nnotations\x18\x02 \x03(\x0b\x32\x0f.FaceAnnotation\x12\x0f\n\x07squared\x18\x03 \x01(\x08\x12\x0f\n\x07padding\x18\x04 \x01(\x05\"\xae\x01\n\x12\x45xtractionResponse\x12\x15\n\roriginalImage\x18\x01 \x01(\t\x12\x38\n\textracted\x18\x02 \x03(\x0b\x32%.ExtractionResponse.AnnotatedPortrait\x1aG\n\x11\x41nnotatedPortrait\x12\r\n\x05image\x18\x01 \x01(\t\x12#\n\nannotation\x18\x02 \x01(\x0b\x32\x0f.FaceAnnotation2B\n\nExtraction\x12\x34\n\x07\x65xtract\x12\x12.ExtractionRequest\x1a\x13.ExtractionResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_EXTRACTIONREQUEST = _descriptor.Descriptor(
  name='ExtractionRequest',
  full_name='ExtractionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='ExtractionRequest.image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='annotations', full_name='ExtractionRequest.annotations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='squared', full_name='ExtractionRequest.squared', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='padding', full_name='ExtractionRequest.padding', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=140,
)


_EXTRACTIONRESPONSE_ANNOTATEDPORTRAIT = _descriptor.Descriptor(
  name='AnnotatedPortrait',
  full_name='ExtractionResponse.AnnotatedPortrait',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='ExtractionResponse.AnnotatedPortrait.image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='annotation', full_name='ExtractionResponse.AnnotatedPortrait.annotation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=317,
)

_EXTRACTIONRESPONSE = _descriptor.Descriptor(
  name='ExtractionResponse',
  full_name='ExtractionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='originalImage', full_name='ExtractionResponse.originalImage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extracted', full_name='ExtractionResponse.extracted', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EXTRACTIONRESPONSE_ANNOTATEDPORTRAIT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=317,
)

_EXTRACTIONREQUEST.fields_by_name['annotations'].message_type = common__pb2._FACEANNOTATION
_EXTRACTIONRESPONSE_ANNOTATEDPORTRAIT.fields_by_name['annotation'].message_type = common__pb2._FACEANNOTATION
_EXTRACTIONRESPONSE_ANNOTATEDPORTRAIT.containing_type = _EXTRACTIONRESPONSE
_EXTRACTIONRESPONSE.fields_by_name['extracted'].message_type = _EXTRACTIONRESPONSE_ANNOTATEDPORTRAIT
DESCRIPTOR.message_types_by_name['ExtractionRequest'] = _EXTRACTIONREQUEST
DESCRIPTOR.message_types_by_name['ExtractionResponse'] = _EXTRACTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExtractionRequest = _reflection.GeneratedProtocolMessageType('ExtractionRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTIONREQUEST,
  '__module__' : 'extraction_pb2'
  # @@protoc_insertion_point(class_scope:ExtractionRequest)
  })
_sym_db.RegisterMessage(ExtractionRequest)

ExtractionResponse = _reflection.GeneratedProtocolMessageType('ExtractionResponse', (_message.Message,), {

  'AnnotatedPortrait' : _reflection.GeneratedProtocolMessageType('AnnotatedPortrait', (_message.Message,), {
    'DESCRIPTOR' : _EXTRACTIONRESPONSE_ANNOTATEDPORTRAIT,
    '__module__' : 'extraction_pb2'
    # @@protoc_insertion_point(class_scope:ExtractionResponse.AnnotatedPortrait)
    })
  ,
  'DESCRIPTOR' : _EXTRACTIONRESPONSE,
  '__module__' : 'extraction_pb2'
  # @@protoc_insertion_point(class_scope:ExtractionResponse)
  })
_sym_db.RegisterMessage(ExtractionResponse)
_sym_db.RegisterMessage(ExtractionResponse.AnnotatedPortrait)



_EXTRACTION = _descriptor.ServiceDescriptor(
  name='Extraction',
  full_name='Extraction',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=319,
  serialized_end=385,
  methods=[
  _descriptor.MethodDescriptor(
    name='extract',
    full_name='Extraction.extract',
    index=0,
    containing_service=None,
    input_type=_EXTRACTIONREQUEST,
    output_type=_EXTRACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXTRACTION)

DESCRIPTOR.services_by_name['Extraction'] = _EXTRACTION

# @@protoc_insertion_point(module_scope)
