# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gateway.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rgateway.proto\x1a\x0c\x63ommon.proto\" \n\x0eGatewayRequest\x12\x0e\n\x06images\x18\x01 \x03(\t\"\xab\x02\n\x0fGatewayResponse\x12\x39\n\x08\x65lements\x18\x01 \x03(\x0b\x32\'.GatewayResponse.ImageWithExtractedData\x1a\xdc\x01\n\x16ImageWithExtractedData\x12\x15\n\roriginalImage\x18\x01 \x01(\t\x12K\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32=.GatewayResponse.ImageWithExtractedData.PortraitWithEmbedding\x1a^\n\x15PortraitWithEmbedding\x12\r\n\x05\x61rray\x18\x01 \x03(\x01\x12\x11\n\tfaceImage\x18\x02 \x01(\t\x12#\n\nannotation\x18\x03 \x01(\x0b\x32\x0f.FaceAnnotation2;\n\x07Gateway\x12\x30\n\telaborate\x12\x0f.GatewayRequest\x1a\x10.GatewayResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_GATEWAYREQUEST = _descriptor.Descriptor(
  name='GatewayRequest',
  full_name='GatewayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='GatewayRequest.images', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=63,
)


_GATEWAYRESPONSE_IMAGEWITHEXTRACTEDDATA_PORTRAITWITHEMBEDDING = _descriptor.Descriptor(
  name='PortraitWithEmbedding',
  full_name='GatewayResponse.ImageWithExtractedData.PortraitWithEmbedding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='array', full_name='GatewayResponse.ImageWithExtractedData.PortraitWithEmbedding.array', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='faceImage', full_name='GatewayResponse.ImageWithExtractedData.PortraitWithEmbedding.faceImage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='annotation', full_name='GatewayResponse.ImageWithExtractedData.PortraitWithEmbedding.annotation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=365,
)

_GATEWAYRESPONSE_IMAGEWITHEXTRACTEDDATA = _descriptor.Descriptor(
  name='ImageWithExtractedData',
  full_name='GatewayResponse.ImageWithExtractedData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='originalImage', full_name='GatewayResponse.ImageWithExtractedData.originalImage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='GatewayResponse.ImageWithExtractedData.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GATEWAYRESPONSE_IMAGEWITHEXTRACTEDDATA_PORTRAITWITHEMBEDDING, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=365,
)

_GATEWAYRESPONSE = _descriptor.Descriptor(
  name='GatewayResponse',
  full_name='GatewayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='elements', full_name='GatewayResponse.elements', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GATEWAYRESPONSE_IMAGEWITHEXTRACTEDDATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=365,
)

_GATEWAYRESPONSE_IMAGEWITHEXTRACTEDDATA_PORTRAITWITHEMBEDDING.fields_by_name['annotation'].message_type = common__pb2._FACEANNOTATION
_GATEWAYRESPONSE_IMAGEWITHEXTRACTEDDATA_PORTRAITWITHEMBEDDING.containing_type = _GATEWAYRESPONSE_IMAGEWITHEXTRACTEDDATA
_GATEWAYRESPONSE_IMAGEWITHEXTRACTEDDATA.fields_by_name['data'].message_type = _GATEWAYRESPONSE_IMAGEWITHEXTRACTEDDATA_PORTRAITWITHEMBEDDING
_GATEWAYRESPONSE_IMAGEWITHEXTRACTEDDATA.containing_type = _GATEWAYRESPONSE
_GATEWAYRESPONSE.fields_by_name['elements'].message_type = _GATEWAYRESPONSE_IMAGEWITHEXTRACTEDDATA
DESCRIPTOR.message_types_by_name['GatewayRequest'] = _GATEWAYREQUEST
DESCRIPTOR.message_types_by_name['GatewayResponse'] = _GATEWAYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GatewayRequest = _reflection.GeneratedProtocolMessageType('GatewayRequest', (_message.Message,), {
  'DESCRIPTOR' : _GATEWAYREQUEST,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:GatewayRequest)
  })
_sym_db.RegisterMessage(GatewayRequest)

GatewayResponse = _reflection.GeneratedProtocolMessageType('GatewayResponse', (_message.Message,), {

  'ImageWithExtractedData' : _reflection.GeneratedProtocolMessageType('ImageWithExtractedData', (_message.Message,), {

    'PortraitWithEmbedding' : _reflection.GeneratedProtocolMessageType('PortraitWithEmbedding', (_message.Message,), {
      'DESCRIPTOR' : _GATEWAYRESPONSE_IMAGEWITHEXTRACTEDDATA_PORTRAITWITHEMBEDDING,
      '__module__' : 'gateway_pb2'
      # @@protoc_insertion_point(class_scope:GatewayResponse.ImageWithExtractedData.PortraitWithEmbedding)
      })
    ,
    'DESCRIPTOR' : _GATEWAYRESPONSE_IMAGEWITHEXTRACTEDDATA,
    '__module__' : 'gateway_pb2'
    # @@protoc_insertion_point(class_scope:GatewayResponse.ImageWithExtractedData)
    })
  ,
  'DESCRIPTOR' : _GATEWAYRESPONSE,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:GatewayResponse)
  })
_sym_db.RegisterMessage(GatewayResponse)
_sym_db.RegisterMessage(GatewayResponse.ImageWithExtractedData)
_sym_db.RegisterMessage(GatewayResponse.ImageWithExtractedData.PortraitWithEmbedding)



_GATEWAY = _descriptor.ServiceDescriptor(
  name='Gateway',
  full_name='Gateway',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=367,
  serialized_end=426,
  methods=[
  _descriptor.MethodDescriptor(
    name='elaborate',
    full_name='Gateway.elaborate',
    index=0,
    containing_service=None,
    input_type=_GATEWAYREQUEST,
    output_type=_GATEWAYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GATEWAY)

DESCRIPTOR.services_by_name['Gateway'] = _GATEWAY

# @@protoc_insertion_point(module_scope)
