name: CI Publication
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/checkout@v2
      - name: Make gradle executable
        run: chmod +x gradlew
      - name: Set up Docker Buildx
        uses: docker/setup-qemu-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: lamba92
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Publish
        id: gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish
        env:
          BINTRAY_API_KEY: ${{secrets.BINTRAYAPIKEY}}
          BINTRAY_USERNAME: ${{secrets.BINTRAYUSERNAME}}
